[package]
name = "amygui"
version = "0.1.0"
edition = "2021"
channel = "nightly"

[dependencies]
raylib = "5.0.2"
amymath = { path = "../amymath" }

[dev-dependencies]
rltest = { path = "../rltest" }
